package edu.fup.ims.rules.test

import edu.fup.ims.services.Service
import edu.fup.ims.services.ServiceInterface
import edu.fup.ims.services.Constraint
import edu.fup.ims.services.InfoType
import edu.fup.ims.services.ConstraintNumberRangeValue
import edu.fup.ims.events.ServiceCallEvent
import edu.fup.ims.events.ParameterValueBinding

function Number toNumber(String value, InfoType infoItem) {

	Number result = null;
	if( infoItem.getDataType() == InfoType.DataType.INT ) {
		result = Integer.parseInt(value); 
	
	}else		
	if( infoItem.getDataType() == InfoType.DataType.FLOAT ) {
		result = Float.parseFloat(value);
	
	}

    return result;
}
 
rule "R01 Type of constraints in a service intarface"
    when
        Service( $serviceInterface : serviceInterface )
    then
        System.out.println( "\n* R01 Type of constraintse service intarface" );
        for( Constraint c: $serviceInterface.getConstraints() )
        {
        	System.out.println( "Type of constraint: " + c.getClass() );
        }
end

rule "R02 Inputs in a service intarface"
    when
        service : Service( $serviceInterface : serviceInterface )
    then
        System.out.println( "\n* R02 Inputs in a service intarface" );
        for( InfoType infoItem : $serviceInterface.getInputs() )
        {
        	System.out.println( "Information item: " + infoItem.getName() );
        	System.out.println( "Value type: " + infoItem.getDataType() );        	
        }
end

rule "R03 Outputs in a service intarface"
    when
        service : Service( $serviceInterface : serviceInterface )
    then
        System.out.println( "\n* R03 Outputs in a service intarfacee" );
        for( InfoType infoItem : $serviceInterface.getOutputs() )
        {
        	System.out.println( "Information item: " + infoItem.getName() );
        	System.out.println( "Value type: " + infoItem.getDataType() );        	
        }
end

rule "R04 contains"
	when
		$infoItem: InfoType(name == "age")
		$serviceInterface: ServiceInterface(outputs contains $infoItem)
	then
		System.out.println( "\n* R04 Collections" );
		System.out.println( "size: " + $serviceInterface.getOutputs().size() );
end

rule "R05 memberOf"
	when
		$infoItem: InfoType(name in ("age","tall") )
		ServiceInterface($outputs : outputs)
		ServiceInterface( $infoItem memberOf $outputs)
	then
		System.out.println( "\n* R05 Collections" );
		System.out.println( "InfoType: " + $infoItem.getName() );		
end

rule "R06 For all"
	when
		forall( $infoItems : InfoType(dataType == DataType.INT ) 
							 InfoType( this == $infoItems, name == "age" ) )
	then
		System.out.println( "\n* R06 For all" );		
end

rule "R07 from"
dialect  "mvel"
	when
		$serviceInterface : ServiceInterface( ) 
		$infoItem : InfoType( dataType == DataType.INT) from $serviceInterface.outputs
	then
		System.out.println( "\n* R07 from" );	
		System.out.println( "$infoItem " + $infoItem.name	 );		
end

/*
rule "R08 ConstraintNumberRangeValue"
dialect  "mvel"
	when
		$serviceInterface : ServiceInterface( ) 
		$infoItem : InfoType( dataType == DataType.INT) from $serviceInterface.outputs
		$constraint : ConstraintNumberRangeValue( InfoType == $infoItem) from $serviceInterface.constraints
	then
		System.out.println( "\n* R08 ConstraintNumberRangeValue" );	
		System.out.println( " $constraint.minValue " + $constraint.minValue	 );
		System.out.println( " $constraint.maxValue " + $constraint.maxValue	 );			
end


rule "ConstraintNumberRangeValue"
dialect  "mvel"
	when
		Service( $serviceName : serviceName, $serviceInterface : serviceInterface )
		ServiceCallEvent( serviceName == $serviceName, $callEventOutputs : outputs )
		
		$infoItem : InfoType( $name : name, dataType in (DataType.INT, DataType.FLOAT) ) from $serviceInterface.outputs				
		$parameterValue : ParameterValueBinding(name == $name, $value : value) from $callEventOutputs		
				
		ConstraintNumberRangeValue( InfoType == $infoItem, maxValue <= toNumber($value,$infoItem) ) from $serviceInterface.constraints

	then
		System.out.println( "\n* R09 ServiceCallEvent" );
		System.out.println( "\t infoItem.name: " + $infoItem.name);
		System.out.println( "\t infoItem.dataType: " + $infoItem.dataType);
		System.out.println( "\t ConstraintNumberRangeValue: " + $value);
						
end
*/